server {
    listen 80;
    root /usr/share/nginx/html;

    # Datoteke z zgoščeno vrednostjo v imenu se ne spreminjajo, zato jih dolgo predpomnimo
    location /static/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Usmerjanje na odjemalcu: neznane poti vrnejo index.html
    location / {
        try_files $uri /index.html;
    }
}
